server:
  port: 8080

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: reativedb
      username: study
      password: 1q2w3e4r
      authentication-database: admin

logging:
  level:
    com.github.parkhuiwo0: DEBUG